---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: phlos
# description will be included in the image's metadata
description: This is my personal OS image based on Bazzite using BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-gnome
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      # copies `files/system/*` (* means everything inside it) into your image's root folder `/`
      - source: system
        destination: /
      # copies `files/my-image/usr/*` to `/usr/` inside the image
      # - source: my-image/usr
      #   destination: /usr

  - type: justfiles
    # validate: true
    # By default, the module will import all files with names ending in .just from files/justfiles/.
    # include:
    #   - common
    #   - gnome/monitors.just
    #   - shared/flatpak/fix-theming.just
    #   - justfile1.just

  - type: chezmoi
    repository: "https://github.com/arcdablid/dotfiles" # my dotfiles repo
    # all-users: false # make users have to enable chezmoi manually
    # file-conflict-policy: replace # override changed files with those from the repo

  - type: dnf
    repos:
      keys:
        - https://linux.teamviewer.com/pubkey/currentkey.asc
      copr:
        - atim/starship
        - scottames/ghostty
    install:
      skip-unavailable: true # skip unavailable packages
      packages:
        - NetworkManager-tui
        - gnome-tweaks

        - starship
        - ghostty

        - xonsh # Python-powered, cross-platform, Unix-gazing shell language and command prompt | https://xon.sh/
        - elvish
        - nu
        - fish
        - zsh

        - shellcheck # Shell script analysis tool | https://github.com/koalaman/shellcheck
        - direnv # Load/unload environment variables based on $PWD | https://direnv.net/
        - parallel # Shell command parallelization utility | https://savannah.gnu.org/projects/parallel/
        - just
        - cheat # Help for various commands and their use cases
        - tealdeer # Very fast implementation of tldr in Rust | https://github.com/dbrgn/tealdeer

        - python3-pip
        - python3-ruamel-yaml # YAML 1.2 loader/dumper package for Python | https://yaml.dev/doc/ruamel.yaml/
        - python3-tqdm # Make your loops show a smart progress meter | https://tqdm.github.io/
        - python3-pyperclip # Cross-platform clipboard module | https://github.com/asweigart/pyperclip
        - python3-validators # Data validation in Python for humans | https://github.com/python-validators/validators/
        - python3-tabulate # Pretty-print tabular data in Python, a library and a command-line utility
        - python3-flask
        - python3-flask-wtf # Simple integration of Flask and WTForms
        - python3-wtforms # Forms validation and rendering library for python

        - java-latest-openjdk.x86_64
        - java-latest-openjdk-devel.x86_64

        - cargo

        - pipx
        - uv # An extremely fast Python package installer and resolver, written in Rust
        - ruff # Extremely fast Python linter and code formatter
        - isort # Sort Python imports automatically | https://pycqa.github.io/isort/
        - black # Python code formatter | https://black.readthedocs.io/en/stable/

        - git
        - micro
        - bat # Clone of cat(1) with syntax highlighting and Git integration | https://github.com/sharkdp/bat
        - moar # Nice to use pager for humans | https://github.com/walles/moar
        - sd # Intuitive find & replace CLI | https://github.com/chmln/sd
        - fzf # Command-line fuzzy finder written in Go | https://github.com/junegunn/fzf
        - util-linux
        - age # File encryption tool | https://github.com/FiloSottile/age
        - httpie # User-friendly cURL replacement (command-line HTTP client) | https://httpie.io/
        - aria2 #Download with resuming and segmented downloading | https://aria2.github.io/
        - mosh # Mobile shell (ssh replacement) - https://mosh.org/
        - gitui # Blazing fast terminal-ui for git written in rust | https://github.com/extrawurst/gitui
        - thefuck
        - glances # Alternative to top/htop | https://nicolargo.github.io/glances/
        - iftop # Display an interface's bandwidth usage | https://pdw.ex-parrot.com/iftop/
        - iperf3 # Update of iperf: measures TCP, UDP, and SCTP bandwidth | https://github.com/esnet/iperf
        - speedtest-cli # Command-line interface for https://speedtest.net bandwidth tests | https://github.com/sivel/speedtest-cli
        - lsof # Utility to list open files | https://github.com/lsof-org/lsof
        - clinfo # Print information about OpenCL platforms and devices | https://github.com/Oblomov/clinfo
        - usbutils # List detailed info about USB devices | http://www.linux-usb.org/
        - pciutils # PCI utilities | https://github.com/pciutils/pciutils
        - ncdu # NCurses Disk Usage | https://dev.yorhel.nl/ncdu
        - dust # More intuitive version of du in rust | https://github.com/bootandy/dust
        - smartmontools # SMART hard drive monitoring | https://www.smartmontools.org/
        - gnupg # GNU Pretty Good Privacy (PGP) package | https://gnupg.org/
        - btop # Resource monitor. C+ homebrew_formula |"version and continuation of bashtop and bpytop | https://github.com/aristocratos/btop
        - fd # Simple, fast and user-friendly alternative to find | https://github.com/sharkdp/fd
        - ack # A grep-like tool tailored to working with large trees of source code | https://beyondgrep.com/
        - eza # Modern, maintained replacement for ls | https://github.com/eza-community/eza
        - gh # GitHub command-line tool | https://cli.github.com/
        - glab # A GitLab CLI tool bringing GitLab to your command line | https://gitlab.com/gitlab-org/cli
        - rclone
        - ripgrep # A line-oriented search tool that recursively searches the current directory for a regex pattern | https://github.com/BurntSushi/ripgrep
        - ugrep # A more powerful, ultra fast, user-friendly, compatible grep | https://github.com/Genivia/ugrep
        - yq # Process YAML, JSON, XML, CSV and properties documents from the CLI | https://github.com/mikefarah/yq
        - jq # Lightweight and flexible command-line JSON processor | https://jqlang.github.io/jq/
        - zoxide # Shell extension to navigate your filesystem faster | https://github.com/ajeetdsouza/zoxide
        - nnn # Tiny, lightning fast, feature-packed file manager | https://github.com/jarun/nnn
        - tree # Display directories as trees (with optional color/HTML output) | https://oldmanprogrammer.net/source.php?dir=projects/tree
        - diffutils # File comparison utilities | https://www.gnu.org/s/diffutils/
        - difftastic # A syntax-aware diff | https://github.com/Wilfred/difftastic
        - glow # Render markdown on the CLI | https://github.com/charmbracelet/glow
        - pandoc # Conversion between documentation formats | https://pandoc.org
        - exiv2 # EXIF and IPTC metadata manipulation library and tools | https://exiv2.org/
        - lolcat # Rainbows and unicorns in your console! | https://github.com/busyloop/lolcat
        - cmatrix # Console Matrix | https://github.com/abishekvashok/cmatrix/
        - qpdf

        - stress # Tool to impose load on and stress test a computer system | https://github.com/resurrecting-open-source-projects/stress
        - stress-ng # Stress test a computer system in various selectable ways | https://wiki.ubuntu.com/Kernel/Reference/stress-ng
        - hyperfine # Command-line benchmarking tool | https://github.com/sharkdp/hyperfine

        - mpv
        - vlc-plugin-bittorrent
        - vlc-plugin-ffmpeg
        - vlc-plugin-pause-click
        - vlc

        - qemu-kvm
        - virt-manager
        - virt-viewer
        - virt-install
        - gnome-boxes

        - podman-tui # terminal user interface for Podman
        - podlet # Generate Podman Quadlet files from a Podman command, compose file, or existing object | https://crates.io/crates/podlet
        - podman-compose # Run docker-compose.yml using podman
        - udica # A tool for generating SELinux security policies for containers | https://github.com/containers/udica
        - skopeo # A command line utility that performs various operations on container images and image repositories | https://github.com/containers/skopeo
        - cosign # A tool for setting up container signing using Sigstore | https://github.com/sigstore/cosign

        - just # A handy way to save and run project-specific commands | https://github.com/casey/just
        - ansible # Automate deployment, configuration, and upgrading | https://www.ansible.com/
        - ansible-lint # Checks ansible playbooks for practices and behaviour | https://ansible-lint.readthedocs.io/
        - butane # Translates human-readable Butane Configs into machine-readable Ignition Configs | https://github.com/coreos/butane

        - gparted

        - ipmitool # Command-line interface to IPMI-enabled devices
        - nethogs
        - nmap # Port scanning utility for large networks | https://nmap.org/
        - wireshark

        - gnome-shell-theme-yaru  # Yaru GNOME Shell Theme
        - yaru-icon-theme         # Yaru icon theme
        - yaru-sound-theme        # Yaru sound theme
        - yaru-theme              # Ubuntu community theme yaru

        - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
        # If no repo information is specified, Flathub will be used by default
      - notify: false
        scope: system
      - notify: false
        scope: user # Also add Flathub user repo, but no user packages

  - type: brew
    # nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - SourceCodePro
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
      # url-fonts:
      #   - name: CustomFont
      #     url: https://example.com/my-font.otf
      #   - name: CompanyFonts
      #     url: https://company.com/fonts.tar.gz

  - type: gnome-extensions
    install:
      # - Night Theme Switcher
      # - Blur my Shell # Notice how extension is named "Blur my Shell" & not "Blur My Shell"?
      #                 # Name is case-sensitive, so check if extension name is typed correctly
      # - AppIndicator and KStatusNotifierItem Support
      # - 307 # Dash-to-Dock
      #       # https://extensions.gnome.org/extension/307/dash-to-dock/
      #       # You can also specify PK ID number from the extension URL,
      #       # if you encounter the scenario where there are multiple extensions with the same name.
      #       # You don't need to look & search for this scenario, since module will automatically fail & inform you to put PK ID number instead
      - 1160 # Dash to Panel | https://github.com/home-sweet-gnome/dash-to-panel
      - 1460 # Vitals | https://github.com/corecoding/Vitals
      - 5470 # Weather O'Clock | https://github.com/CleoMenezesJr/weather-oclock
      - 7065 # Tiling Shell | https://github.com/domferr/tilingshell
      - 8745 # App Grid Tuner | https://codeberg.org/m-lab/app-grid-tuner
    # uninstall:
    #   - GSConnect # Uninstall step here should be used only for the extensions
    #               # which are not installed through OS package manager in the base image,
    #               # like extensions installed from gnome-extensions module

  # - type: bling
  #   install:
  #     - dconf-update-service # a service unit that updates the dconf db on boot
  #     - gnome-vrr # enables gnome-vrr for your image

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - phlos-signed-autorebase.service
        - podman.socket
        - docker.socket
        - tailscaled.service
        - phlos-system-autoclean.timer
    #   disabled:
    #     - flatpak-system-update.timer
    user:
      enabled:
        - notify-signed-autorebase-in-progress.service
    #   disabled:
    #     - flatpak-user-update.timer

  - type: script
    snippets:
      - "mkdir -pv -m 0754 /etc/phlos-autorebase"
      - "flatpak remote-modify --default-branch=stable flathub"
      # - "curl https://example.com/examplebinary > /usr/bin/examplebinary" # example: download binary
      # - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld" # example: ld alternatives symlink workaround
    scripts:
      # run files/scripts/virtualbox.sh
      - virtualbox.sh
