#!/usr/bin/env bash
set -euo pipefail

# Description: Add and remove programs to autostart directory.
# Dependencies: fzf
# Original code by: Derek Taylor @ https://www.gitlab.com/dwt1/fzscripts

# ------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"

declare -a required_cmds=( "fzf" )

for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "${BRed}[${executor}] ::ERROR:: '${rc}' command not available! ${Color_Off}"
        exit
    fi
done

# ------------------------------------------------------------------------------

# The FMENU variable contains the 'fzf' command with our settings.
# Note that the last setting is 'prompt' which is left empty.
# You add the prompt when you invoke $FMENU. For example: $FMENU "my prompt"
FMENU="fzf --header=$(basename "$0") \
           --layout=reverse \
           --exact \
           --border=bold \
           --border=rounded \
           --margin=5% \
           --multi \
           --color=dark \
           --height=95% \
           --info=hidden \
           --header-first \
           --bind change:top \
           --prompt"

autostart_files=()
for dir in $HOME/.config/autostart/; do
    if [ -d "$dir" ]; then
        # Using -printf "%f\n" to get filenames without full path.
        autostart_files+=("$(find "$dir" -type f -printf "%f\n")")
    fi
done

desktop_files=()
dirs=$(echo "$XDG_DATA_DIRS" | sed 's/:/\/applications /g')
for dir in ${dirs}; do
    if [ -d "$dir" ]; then
        # The -print is the default for 'find' so not needed.
        # The -print contains the full path which is needed for later.
        desktop_files+=("$(find "$dir" -type f -print)")
    fi
done

# Lists all files within the autostart directory.
listauto() {
    tput setaf 6 bold
    printf "%s\n" "Programs currently in autostart directory:"
    tput sgr0
    tree ~/.config/autostart/ | grep -e '├' -e '└' --color=never
}

# Lists the desktop files allowing user to add selections to autostart directory.
addauto() {
    if [ ! -d "$HOME"/.config/autostart ]; then
        mkdir -p "$HOME"/.config/autostart || echo "$HOME/.config/autostart does not exist."
    fi

    selected_file=$($FMENU "Add program to autostart: " < <(printf "%s\n" "${desktop_files[@]}"))
    if [[ -n "$selected_file" ]]; then
        selected_array=$selected_file
        for i in "${selected_array[@]}"; do
            tput setaf 5 bold
            printf "%s" "✓ "
            tput setaf 5 bold
            cp "$i" ~/.config/autostart/
            printf "%s" "$(basename "$i")"
            tput sgr0
            printf "%s\n\n" " added to autostart directory."
        done
    else
        echo "No options selected."
    fi
}

# Lists all files within the autostart directory allowing user to remove selections.
rmauto() {
    selected_file=$($FMENU "Remove program from autostart: " < <(printf "%s\n" "${autostart_files[@]}"))

    if [[ -n "$selected_file" ]]; then
        selected_array=$selected_file
        for i in "${selected_array[@]}"; do
            tput setaf 9 bold
            printf "%s" "✗ "
            tput setaf 9 bold
            rm ~/.config/autostart/"$i"
            printf "%s" "$(basename "$i")"
            tput sgr0
            printf "%s\n\n" " removed from autostart directory."
        done
    else
        echo "No options selected."
    fi
}

while getopts "alrh" arg 2>/dev/null; do
    case "${arg}" in
    a)
        addauto
        listauto
        exit
        ;;
    l)
        listauto
        exit
        ;;
    r)
        rmauto
        listauto
        exit
        ;;
    h)
        printf "Usage: auto [options]
Description: Add/remove programs for autostart.
Dependencies: fzf
Note: Make a single selection by pressing ENTER or multiple selections by pressing SHIFT+TAB.

The folowing OPTIONS are accepted:
    -h  displays this help page
    -a  add programs to autostart directory
    -l  list contents of autostart directory
    -r  remove programs from autostart directory

Running startup without any arguments will prompt you to choose an option.
It will then rerun the script with the correct option.
Run 'man auto' for more information\n"
        exit
        ;;
    *)
        printf '%s\n' "Error: invalid option" "Type '$(basename "$0") -h' for help" ;;
    esac
    no_opt=0
done

if [ $# -eq 0 ]; then
    options=("Add a program to autostart" "Remove a program from autostart" "List contents of autostart directory" "Get help information about this program" "Quit")
    menu=$($FMENU "What do you want to do? " < <(printf "%s\n" "${options[@]}"))
    selection=$menu
    case $selection in
        "Add a program to autostart")
            $0 -a
            exit
            ;;
        "Remove a program from autostart")
            $0 -r
            exit
            ;;
        "List contents of autostart directory")
            $0 -l
            exit
            ;;
        "Get help information about this program")
            $0 -h
            exit
            ;;
        "Quit")
            exit
            ;;
    esac
fi