#!/usr/bin/env python

import argparse
import pathlib

parser = argparse.ArgumentParser(
    description="Normalize input paths",
    formatter_class=argparse.RawDescriptionHelpFormatter,
)

parser.add_argument(
    "paths",
    metavar="P",
    type=str,
    nargs="+",
    help="path to file/folder",
)

args = parser.parse_args()

for p in args.paths:
    p = pathlib.Path(f"{p}").expanduser().resolve()
    print(f"{str(p)}")
