#!/usr/bin/env bash
set -euo pipefail

executor="${0##*/}"

if [[ ! -d /tmp/nerd-fonts ]]; then
    git clone --filter=blob:none --sparse git@github.com:ryanoasis/nerd-fonts /tmp/nerd-fonts
else
    git -C /tmp/nerd-fonts pull
fi

git -C /tmp/nerd-fonts sparse-checkout add patched-fonts/"${1}"
/tmp/nerd-fonts/install.sh "${1}"