#!/usr/bin/env bash
set -euo pipefail

# Modified version of:
# https://github.com/markusressel/zfs-inplace-rebalancing

# ------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

function expand_path {
    python3 - "$@" << EOF
import argparse
import pathlib

parser = argparse.ArgumentParser(
    description="Normalize input paths",
    formatter_class=argparse.RawDescriptionHelpFormatter,
)

parser.add_argument(
    "paths",
    metavar="P",
    type=str,
    nargs="+",
    help="path to file/folder",
)

args = parser.parse_args()

for p in args.paths:
    p = pathlib.Path(f"{p}").expanduser().resolve()
    print(f"{str(p)}")
EOF
}

function print_char_line {
    local filler=${1}
    printf "%`tput cols`s" | sed "s/ /${filler}/g"
    printf '\n'
}

# ------------------------------------------------------------------------------

# print a help message
function print_usage {
    echo "Usage: zfs-inplace-rebalancing --checksum true --skip-hardlinks false --passes 1 /my/pool"
}

# print a given text entirely in a given color
function color_echo {
    color=$1
    text=$2
    echo -e "${color}${text}${Color_Off}"
}

# rebalance a specific file
function rebalance {
    local script_name="$FUNCNAME"

    function rebalance-usage {
        >&2 cat << EOF
Usage: $0
    [-f/--failed_items]             Path to file logging failed items.

    [-r/--rebalance_db_file_name]   Path to db file logging rebalanced items.

    [-l/--skip_hardlinks_flag]      Skip hardlinks flag.

    [-p/--passes_flag]              Passes flag.

    <file> [file]
EOF
    }

    local failed_items=""
    local rebalance_db_file_name=""
    local skip_hardlinks_flag=""
    local passes_flag=""
    local checksum_flag=""

    local args=$(getopt -a -o f:r:l:p:c: --long failed_items:,rebalance_db_file_name:,skip_hardlinks_flag:,passes_flag:,checksum_flag: -- "$@")
    if [[ $? -gt 0 ]]; then
        rebalance-usage
        exit 1
    fi

    eval set -- ${args}
    while :
    do
        case $1 in


            -f | --failed_items             )   failed_items="${2}"
                                                shift 2
                                                ;;
            -r | --rebalance_db_file_name   )   rebalance_db_file_name="${2}"
                                                shift 2
                                                ;;
            -l | --skip_hardlinks_flag      )   skip_hardlinks_flag="${2}"
                                                shift 2
                                                ;;
            -p | --passes_flag              )   passes_flag="${2}"
                                                shift 2
                                                ;;
            -c | --checksum_flag            )   checksum_flag="${2}"
                                                shift 2
                                                ;;
            # -- means the end of the arguments; drop this, and break out of the while loop
            --  )   shift; break
                    ;;
            *   )   printf "[${script_name}] ${BRed}::ERROR::${Color_Off} Unsupported option: %s\n" "${1}"
                    rebalance-usage
                    exit 1
                    ;;
        esac
    done

    if [[ $# -eq 0 ]]; then
        printf "[${script_name}] ${BRed}::ERROR::${Color_Off} No paths provided!\n"
        rebalance-usage
        exit 1
    else
        declare -a file_paths=( "$@" )
        for file_path in "${file_paths[@]}"; do

            if [[ ! -f "${file_path}" ]]; then
                printf "${BRed}Missing: %s${Color_Off}\n" "${file_path}"
                printf 'Missing: %s\n' "${file_path}" | tee --append "${failed_items}" > /dev/null
                continue
            fi

            # double check if file has >=2 links in the case of --skip-hardlinks
            # this shouldn't be needed in the typical case of `find` only finding files with links == 1
            if [[ "${skip_hardlinks_flag,,}" == "true"* ]]; then

                #  -c  --format=FORMAT
                #      use the specified FORMAT instead of the default; output a
                #      newline after each use of FORMAT
                #  %h     number of hard links
                local hardlink_count=$(stat -c "%h" "${file_path}")

                if [[ "${hardlink_count}" -ge 2 ]]; then
                    printf "${BYellow}Hardlink: %s${Color_Off}\n" "${file_path}"
                    printf 'Hardlink: %s\n' "${file_path}" | tee --append "${failed_items}" > /dev/null
                    continue
                fi
            fi

            if [[ "${passes_flag}" -ge 1 ]]; then
                # check if target rebalance count is reached

                #----
                # local line_nr=$(grep -xF -n "${file_path}" "${rebalance_db_file_name}" | head -n 1 | cut -d: -f1)
                # if [ -z "${line_nr}" ]; then
                #     local rebalance_count="0"
                # else
                #     local rebalance_count_line_nr="$((line_nr + 1))"
                #     local rebalance_count=$(awk "NR == ${rebalance_count_line_nr}" "${rebalance_db_file_name}")
                # fi
                #----

                local rebalance_count=$( grep "${file_path}" "${rebalance_db_file_name}" | head -n 1 | cut -d '|' -f 1 )

                if [[ "${rebalance_count}" -ge "${passes_flag}" ]]; then
                    # color_echo "${Yellow}" "Rebalance count (${passes_flag}) reached, skipping: ${file_path}"
                    printf "${BBlue}Rebalance count (%s) reached: %s${Color_Off}\n" "${passes_flag}" "${file_path}"
                    continue
                fi
            fi

            local tmp_extension=".balance"
            local tmp_file_path="${file_path}${tmp_extension}"

            # echo "Copying '${file_path}' to '${tmp_file_path}'..."

            # --reflink=never -- force standard copy (see ZFS Block Cloning)
            # -a -- keep attributes, includes -d -- keep symlinks (dont copy target) and -p -- preserve ACLs to
            # -x -- stay on one system
            cp --reflink=never -ax "${file_path}" "${tmp_file_path}"

            # compare copy against original to make sure nothing went wrong
            if [[ "${checksum_flag,,}" == "true"* ]]; then
                # echo "Comparing copy against original..."

                # file attributes
                local original_md5=$(lsattr "${file_path}" | awk '{print $1}')
                # file permissions, owner, group
                # shellcheck disable=SC2012
                original_md5="${original_md5} $(ls -lha "${file_path}" | awk '{print $1 " " $3 " " $4}')"
                # file content
                original_md5="${original_md5} $(md5sum -b "${file_path}" | awk '{print $1}')"

                # file attributes
                local copy_md5=$(lsattr "${tmp_file_path}" | awk '{print $1}')
                # file permissions, owner, group
                # shellcheck disable=SC2012
                copy_md5="${copy_md5} $(ls -lha "${tmp_file_path}" | awk '{print $1 " " $3 " " $4}')"
                # file content
                copy_md5="${copy_md5} $(md5sum -b "${tmp_file_path}" | awk '{print $1}')"

                if [[ ! "${original_md5}" == "${copy_md5}"* ]]; then
                    printf "${BRed}MD5 fail: %s -> %s != %s${Color_Off}\n" "${file_path}" "${original_md5}" "${copy_md5}"
                    printf 'MD5 fail: %s -> %s != %s\n' "${file_path}" "${original_md5}" "${copy_md5}" | tee --append "${failed_items}" > /dev/null
                    continue
                fi
            fi

            # echo "Removing original '${file_path}'..."
            rm "${file_path}"

            # echo "Renaming temporary copy to original '${file_path}'..."
            mv "${tmp_file_path}" "${file_path}"

            if [[ "${passes_flag}" -ge 1 ]]; then
                # update rebalance "database"
                if grep -q "${file_path}" "${rebalance_db_file_name}" ; then
                    rebalance_count="$((rebalance_count + 1))"
                    sed -i "s%.*${file_path}%${rebalance_count}|${file_path}%g" "${rebalance_db_file_name}"
                else
                    rebalance_count=1
                    printf '%d|%s\n' ${rebalance_count} "${file_path}" | tee --append "${rebalance_db_file_name}" > /dev/null
                fi
            fi

            # printf "${BGreen}Rebalanced: %s${Color_Off}\n" "${file_path}"
        done
    fi
}

# ------------------------------------------------------------------------------

# file used to track processed files
rebalance_db_file_name="$( expand_path "./rebalance_db.txt" )"

# index used for progress
current_index=0

checksum_flag='true'
skip_hardlinks_flag='false'
passes_flag='1'

if [[ "$#" -eq 0 ]]; then
    print_usage
    exit 0
fi

while true ; do
    case "$1" in
        -h | --help )
            print_usage
            exit 0
        ;;
        -c | --checksum )
            if [[ "$2" == 1 || "$2" =~ (on|true|yes) ]]; then
                checksum_flag="true"
            else
                checksum_flag="false"
            fi
            shift 2
        ;;
        -l | --skip-hardlinks )
            if [[ "$2" == 1 || "$2" =~ (on|true|yes) ]]; then
                skip_hardlinks_flag="true"
            else
                skip_hardlinks_flag="false"
            fi
            shift 2
        ;;
        -p | --passes )
            passes_flag=$2
            shift 2
        ;;
        *)
            break
        ;;
    esac
done;

root_path="$( expand_path "$1" )"

if [[ ! -e "${root_path}" ]]; then
    printf "[${script_name}] ${BRed}::ERROR::${Color_Off} Path not found: %s\n" "${root_path}"
    exit 1
fi

color_echo "$Cyan" "Start rebalancing $(date):"
color_echo "$Cyan" "  Path: ${root_path}"
color_echo "$Cyan" "  Rebalancing Passes: ${passes_flag}"
color_echo "$Cyan" "  Use Checksum: ${checksum_flag}"
color_echo "$Cyan" "  Skip Hardlinks: ${skip_hardlinks_flag}"

# recursively scan through files
# in the case of --skip-hardlinks, only find files with links == 1
# if [[ "${skip_hardlinks_flag,,}" == "true"* ]]; then
#     mapfile -t find_files < <( find "${root_path}" -type f -links 1 )
# else
#     mapfile -t find_files < <( find "${root_path}" -type f  )
# fi

# create db file
if [ "${passes_flag}" -ge 1 ]; then
    touch "${rebalance_db_file_name}"
fi

failed_items="$( mktemp )"
trap "rm -f ${failed_items}" 0 2 3 15   # 0/EXIT = Exit shell, 2/SIGINT = Interrupt, 3/SIGQUIT = Quit, 15/SIGTERM = Terminate
                                        # https://man7.org/linux/man-pages/man7/signal.7.html
                                        # https://unix.stackexchange.com/a/181939

rust_parallel_cmds="$( mktemp )"
trap "rm -f ${rust_parallel_cmds}" 0 2 3 15 # 0/EXIT = Exit shell, 2/SIGINT = Interrupt, 3/SIGQUIT = Quit, 15/SIGTERM = Terminate
                                            # https://man7.org/linux/man-pages/man7/signal.7.html
                                            # https://unix.stackexchange.com/a/181939

if [[ "${skip_hardlinks_flag,,}" == "true"* ]]; then
    find "${root_path}" -type f -links 1 -exec printf 'rebalance -r "%s" -f "%s" -l "%s" -p "%s" -c "%s" -- "%s"\n' "${rebalance_db_file_name}" "${failed_items}" "${skip_hardlinks_flag}" "${passes_flag}" "${checksum_flag}" "{}" \; > "${rust_parallel_cmds}"
else
    find "${root_path}" -type f -exec printf 'rebalance -r "%s" -f "%s" -l "%s" -p "%s" -c "%s" -- "%s"\n' "${rebalance_db_file_name}" "${failed_items}" "${skip_hardlinks_flag}" "${passes_flag}" "${checksum_flag}" "{}" \; > "${rust_parallel_cmds}"
fi

# head -n 20 "${rust_parallel_cmds}"
# exit 0

# for ff in "${find_files[@]}"; do
#     printf 'rebalance -r "%s" -f "%s" -l "%s" -p "%s" -c "%s" -- "%s"\n' "${rebalance_db_file_name}" "${failed_items}" "${skip_hardlinks_flag}" "${passes_flag}" "${checksum_flag}" "${ff}" | tee --append "${rust_parallel_cmds}" > /dev/null
# done

color_echo "$Cyan" "  File Count: $( wc -l < "${rust_parallel_cmds}" )"

export -f rebalance
# --discard-output all
# --progress-bar
rust-parallel --shell --jobs 4 --input-file "${rust_parallel_cmds}"
unset -f rebalance

if [[ -f "${failed_items}" ]]; then
    line_count=$( wc -l < "${failed_items}" )
    if [[ "${line_count}" -gt 0 ]]; then
        echo
        print_char_line '='
        printf "${BRed}Failed items:${Color_Off} %s\n" "${line_count}"
        cat "${failed_items}"
    fi
    unset line_count
fi

echo ""
echo ""
color_echo "$Green" "Done!"
